import type { Metadata } from "next";
import "./globals.css";
import NavbarHome from "@/component/NavbarHome";
import Footer from "@/component/footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <NavbarHome />
        {children}
        <Footer />
      </body>
    </html>
  );
}
