import type { Metadata } from "next";
import "./globals.css";
import NavbarHome from "@/component/NavbarHome";
import Footer from "@/component/footer";
import { ThemeProvider } from "@/context/ThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body >
        <ThemeProvider>
           <NavbarHome />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
